config/routes.rb
SampleApplication::Application.routes.draw do

  get "chats/index"
  get "chats/send_data"

  get "networks/index"
  get "networks/edit"

  get "emails/remind"
  get "emails/correspond"

  get "friendships/initiate"
  get "friendships/accept"
  get "friendships/decline"
  get "friendships/cancel"
  get "friendships/delete"

  get "faqs/index"
  get "faqs/edit"

  resources :emails do
    member do
      get "correspond" #enable using rout helper 'correspond_email_path' 
    end
  end

  resources :faqs
  resources :specs

  resources :users do
    member do
      get :friends
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :profiles
  resources :friendships
  resources :networks
  resources :chats
  resources :preferences
  resources :posts

  match "/signup", :to=> "users#new"
  match "/signin", :to => "sessions#new"
  match "/signout", :to => "sessions#destroy"
  match "/home", :to=>"pages#home"
  match "/help", :to =>"pages#help"
  match "/contact", :to =>"pages#contact"
  match "/about", :to =>"pages#about"
  match "/request", :to =>"friendships#create"
  match "/emails/remind", :to =>"emails#remind"
  match "/emails/correspond", :to => "emails#correspond"
  match "/friendships/initiate", :to => "friendships#initiate"
  match "/friendships/accept", :to => "friendships#accept"
  match "/friendships/delete", :to => "friendships#delete"
  match "/chats/send_data", :to => "chats#send_data"
  match "/preferences/edit", :to => "preferences#edit"
  match "/preferences/show", :to => "preferences#show"

  root :to => "pages#home"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User",
              :foreign_key => "friend_id"
  validates :user_id, :presence => true
  validates :friend_id, :presence => true

  #returns true if friendship process ongoing or done
  def self.exists?(user, friend)
    not find_by_user_id_and_friend_id(user, friend).nil?
  end

  def self.request(user, friend) 
    unless user == friend or Friendship.exists?(user, friend)
      transaction do
        create(:user=>user, :friend=>friend, :status=>"pending")
        create(:user=>friend, :friend=>user, :status=>"requested")
      end
    end
  end

  #Accept a friend request
  def self.accept(user,friend)
    transaction do
      accepted_at = Time.now
      accept_one_side(user, friend, accepted_at)
      accept_one_side(friend, user, accepted_at)
    end
  end

  #Destroy a friendship or cancel a pending one
  def self.breakup(user, friend)
    transaction do
      destroy(find_by_user_id_and_friend_id(user, friend))
      destroy(find_by_user_id_and_friend_id(friend, user))

    end
  end

  private
    #Update the db with one side of an accepted friendship
  def self.accept_one_side(user, friend, accepted_at)
    request = find_by_user_id_and_friend_id(user, friend)
    request.status = 'accepted'
    request.accepted_at = accepted_at
    request.save!
  end
end


# == Schema Information
#
# Table name: friendships
#
#  id           :integer         not null, primary key
#  user_id      :integer
#  friend_id    :integer
#  status       :string(255)
#  initiated_at :datetime
#  accepted_at  :datetime
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authenticate, :setup_friends

  def initiate
    Friendship.request(@user, @friend)
    UserMailer.friend_request(@user, @friend).deliver
    flash[:success] = "Friend request sent to #{@friend.email}"
    redirect_to profile_path(@friend)

  end

  def accept
    if @user.requested_friends.include?(@friend)
      Friendship.accept(@user, @friend)
      flash[:success] = "Friendship with #{@friend.name} accepted!"
    else
      flash[:error] = "No friendship request from #{@friend.name}"
    end
    redirect_to profile_path(@user)
  end

  def decline
    if @user.requested_friends.include?(@friend)
      Friendship.breakup(@user, @friend)
      flash[:success] = "Friendship with #{@friend.name} declined!"
    else
      flash[:error] = "No friendship request from #{@friend.name}"
    end
    redirect_to profile_path(@user)
  end
  
  def cancel
    if @user.pending_friends.include?(@friend)
      Friendship.breakup(@user, @friend)
      flash[:success] = "Friendship with #{@friend.name} cancelled!"
    else
      flash[:error] = "No request for friendship with #{@friend.name}"
    end
    redirect_to profile_path(@user)
  end

  def delete
    if @user.friends.include?(@friend)
      Friendship.breakup(@user, @friend)
      flash[:success] = "Friendship with #{@friend.name} deleted!"
    else
      flash[:error] = "You are not yet friends with #{@friend.name}"
    end
    redirect_to profile_path(@user)
  end

  def show
    @user = User.find(params[:id])
    @friends = @user.friends.paginate :page => params[:page]

    if @friends.empty?
      flash[:notice] = "There are no friends to display"
      redirect_to profile_path(@user)
    end

  end

  private 

  #initialize current user and friend
  def setup_friends
    @user = current_user
    @friend = User.find(params[:id])
  end

  
end

app/helpers/friendships_helper.rb
module FriendshipsHelper

  #return an appropriate friendship status message
  def friendship_status(user, friend)
    friendship = Friendship.find_by_user_id_and_friend_id(user, friend)
    return "#{friend.name} is not your friend yet." if friendship.nil?
    case friendship.status
    when 'requested'
      "#{friend.name} would like to connect to you."
    when 'pending'
      "Friend requested from #{friend.name}"
    when 'accepted'
      "#{friend.name} is your friend."
    end

  end

  #displays which action to take depending on friendship status
  def friendship_action(user, friend)
    #return "me" if User.is_same?(user, friend)
    return "me" if current_user?(friend)
    friendship = Friendship.find_by_user_id_and_friend_id(user, friend)
    return link_to "Add friend", {:controller =>"friendships",
      :action =>"initiate", :id => friend.id},
      :confirm =>"Add #{friend.name}?" if friendship.nil? 

    case friendship.status
    when 'requested'
      "awaiting ur approval"
    when 'pending'
      "sent request"
    end
  end


  #returns a mutual friends list or an empty array if there are none 
  def mutual_friends user
    unless current_user.friends.empty? or user.friends.empty?
      #returns the intersection of the 2 arrays which represents mutual friends
      user.friends & current_user.friends
    else
      []
    end
  end

end

app/views/friendships/_friend.haml
#friend.span-1
  = link_to (gravatar_for friend, :size => 35), profile_path(friend)
  -#%br/
  -#= link_to friend.name, profile_path(friend)

  -#= link_to friend.name, profile_path(friend)
  -#- unless hide_edit_links?
    -#= link_to "remove", {:controller => "friendships",
      -#:action => "delete", :id => friend.id},
        -#:confirm => "Delete friendship with #{friend.name}?"

app/views/friendships/_friends.haml
#friends-count
  = link_to (pluralize(@friends.count,"friend"), friends_user_path(@user))
  %hr/
#friends
  - @friends.each do |friend|
    = render "friendships/friend", :friend => friend
-unless @requested_friends.empty? or hide_edit_links?

  #requested-friends-count
    = pluralize(@requested_friends.count, "requesting friend")
    %hr/
  #requested-friends
    - @requested_friends.each do |requested_friend|
      = render "friendships/requested_friend", :requested_friend => requested_friend

-unless @pending_friends.empty? or hide_edit_links?
  #pending-friends-count
    %hr/
    = pluralize(@pending_friends.count, "requested friend")
    %hr/
  #pending-friends
    - @pending_friends.each do |pending_friend|
      = render "friendships/pending_friend", :pending_friend => pending_friend

app/views/friendships/_mutual_friends.haml
%hr/
= pluralize(mutual_friends(@user).count, "mutual friend")
%hr/
- mutual_friends(@user).each do |mutual_friend|
  -#.mutual_friends
  = link_to (gravatar_for mutual_friend, :size => 40),
          profile_path(mutual_friend)

app/views/friendships/_pending_friend.haml
%tr
  %td
    = gravatar_for pending_friend, :side => 30
    = link_to pending_friend.name, profile_path(pending_friend)
  %td
    = link_to "Cancel", {:controller => "friendships",
      :action => "cancel", :id => pending_friend.id},
      :confirm => "Cancel friendship with #{pending_friend.name}?"

app/views/friendships/_requested_friend.haml
%tr
  %td
    = gravatar_for requested_friend, :size => 30
    = link_to requested_friend.name, profile_path(requested_friend)
  %td
    = link_to "Accept", {:controller => "friendships",
          :action => "accept", :id => requested_friend.id}
    = link_to "Decline", {:controller => "friendships",
      :action => "decline", :id => requested_friend.id},
      :confirm => "Turn down friendship with #{requested_friend.name}?"

app/views/friendships/show.haml
= will_paginate @friends
%fieldset
  %legend
    All friends
  %table
    - @friends.each do |friend|
      %tr
        %td
          = friend.name
= will_paginate @friends