config/routes.rb
SampleApplication::Application.routes.draw do

  get "chats/index"
  get "chats/send_data"

  get "networks/index"
  get "networks/edit"

  get "emails/remind"
  get "emails/correspond"

  get "friendships/initiate"
  get "friendships/accept"
  get "friendships/decline"
  get "friendships/cancel"
  get "friendships/delete"

  get "faqs/index"
  get "faqs/edit"

  resources :emails do
    member do
      get "correspond" #enable using rout helper 'correspond_email_path' 
    end
  end

  resources :faqs
  resources :specs

  resources :users do
    member do
      get :friends
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :profiles
  resources :friendships
  resources :networks
  resources :chats
  resources :preferences
  resources :posts

  match "/signup", :to=> "users#new"
  match "/signin", :to => "sessions#new"
  match "/signout", :to => "sessions#destroy"
  match "/home", :to=>"pages#home"
  match "/help", :to =>"pages#help"
  match "/contact", :to =>"pages#contact"
  match "/about", :to =>"pages#about"
  match "/request", :to =>"friendships#create"
  match "/emails/remind", :to =>"emails#remind"
  match "/emails/correspond", :to => "emails#correspond"
  match "/friendships/initiate", :to => "friendships#initiate"
  match "/friendships/accept", :to => "friendships#accept"
  match "/friendships/delete", :to => "friendships#delete"
  match "/chats/send_data", :to => "chats#send_data"
  match "/preferences/edit", :to => "preferences#edit"
  match "/preferences/show", :to => "preferences#show"

  root :to => "pages#home"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :poster_id 

  belongs_to :user
  belongs_to :poster, :class_name => "User", :foreign_key => "poster_id"
  has_many :comments, :dependent => :destroy

  validates :content, :presence => true,
    :length => {:maximum => 255}
  validates :user_id, :presence => true
  validates :poster_id, :presence => true

  default_scope :order =>"posts.created_at DESC" #display most current posts first 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate

  #respond_to :html, :js

  def index

  end
  def show

  end

  def create
    @user = User.find(params[:post][:user_id]) #the user on whose wall the post was written 
    @post = @user.posts.create!(:poster_id => current_user.id, :content=>
                       params[:post][:content])
    respond_to do |format|
      format.html {redirect_to profile_path(@user)}
      format.js
    end
    #redirect_to profile_path(@user) #redirecting to the user on whose wall content was posted. 

  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(@post.poster_id)
    @post.destroy
    redirect_to profile_path(@user)
    #respond_with profile_path(@user)

    #respond_to do |format|
      #format.html {redirect_to profile_path(@user)}
      #format.js
    #end

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.haml
%tr
  %td
    %span
      = div_for post do
        -#-if current_user?(@user)
        = link_to gravatar_for(post.poster, :size =>50), profile_path(post.poster)
        = link_to post.poster.name, profile_path(post.poster)
      -#- else if post.poster != current_user
        -#Posted on ur wall.
    %span
      %br/
      = post.content
      %br/
    %span
      Posted
      = time_ago_in_words post.created_at
      ago.
      = link_to "delete", post_path(post), :method => :delete, 
        :class => "delete", :remote => true if current_user?(@user)

app/views/posts/create.js.erb
<%#$("post-table").update("<%= escape_javascript(render @posts) %>")%>
<%#$("post-table").html("<%= escape_javascript(render 'profiles/wall_posts', %>
                                    <%#:locals=>{:wall_post=>wall_post}) %>")%>

$("#post-table").append("<%= escape_javascript render(@post) %>");